server:
  port: 8081
  servlet:
    context-path: /discovery/

spring:
  application:
    name: discovery
  redis:
    database: 0
    host: 192.168.188.128
    port: 6379
    timeout: PT10S
#    password: 密码
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 50
        # 连接池中的最大空闲连接 默认 8
        max-idle: 20
        # 连接池中的最小空闲连接 默认 0
        min-idle: 1
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认 -1，这里配置10s
        max-wait: PT10S


